export const brandDomains = {
Acura: "acura.com",
"Alfa Romeo": "alfaromeousa.com",
"AM General": "amgeneral.com",
"Aston Martin": "astonmartin.com",
Audi: "audi.com",
Bentley: "bentleymotors.com",
BMW: "bmw.com",
Bugatti: "bugatti.com",
Buick: "buick.com",
Cadillac: "cadillac.com",
Chevrolet: "chevrolet.com",
Chrysler: "chrysler.com",
Dodge: "dodge.com",
Ferrari: "ferrari.com",
FIAT: "fiatusa.com",
Ford: "ford.com",
Genesis: "genesis.com",
GMC: "gmc.com",
Honda: "honda.com",
HUMMER: "hummer.com",
Hyundai: "hyundai.com",
INFINITI: "infinitiusa.com",
Isuzu: "isuzu.com",
Jaguar: "jaguarusa.com",
Jeep: "jeep.com",
Kia: "kia.com",
Lamborghini: "lamborghini.com",
"Land Rover": "landroverusa.com",
Lexus: "lexus.com",
Lincoln: "lincoln.com",
Maserati: "maserati.com",
Mazda: "mazdausa.com",
McLaren: "cars.mclaren.com",
"Mercedes-Benz": "mbusa.com",
MINI: "miniusa.com",
Mitsubishi: "mitsubishicars.com",
Nissan: "nissanusa.com",
Polestar: "polestar.com",
Pontiac: "pontiac.com",
Porsche: "porsche.com",
Ram: "ramtrucks.com",
Rivian: "rivian.com",
"Rolls-Royce": "rolls-roycemotorcars.com",
Saab: "saab.com",
Saturn: "saturn.com",
Scion: "scion.com",
smart: "smartusa.com",
Subaru: "subaru.com",
Suzuki: "suzuki.com",
Tesla: "tesla.com",
Toyota: "toyota.com",
Volkswagen: "vw.com",
Volvo: "volvocars.com",
};
